/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ApiShareRouteImport } from './routes/api.share'
import { Route as ApiRawIdRouteImport } from './routes/api.raw.$id'
import { Route as ApiOgIdRouteImport } from './routes/api.og.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareRoute = ApiShareRouteImport.update({
  id: '/api/share',
  path: '/api/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRawIdRoute = ApiRawIdRouteImport.update({
  id: '/api/raw/$id',
  path: '/api/raw/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIdRoute = ApiOgIdRouteImport.update({
  id: '/api/og/$id',
  path: '/api/og/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/share': typeof ApiShareRoute
  '/s/$id': typeof SIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/raw/$id': typeof ApiRawIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/share': typeof ApiShareRoute
  '/s/$id': typeof SIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/raw/$id': typeof ApiRawIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/share': typeof ApiShareRoute
  '/s/$id': typeof SIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/raw/$id': typeof ApiRawIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/share' | '/s/$id' | '/api/og/$id' | '/api/raw/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/share' | '/s/$id' | '/api/og/$id' | '/api/raw/$id'
  id:
    | '__root__'
    | '/'
    | '/api/share'
    | '/s/$id'
    | '/api/og/$id'
    | '/api/raw/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiShareRoute: typeof ApiShareRoute
  SIdRoute: typeof SIdRoute
  ApiOgIdRoute: typeof ApiOgIdRoute
  ApiRawIdRoute: typeof ApiRawIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share': {
      id: '/api/share'
      path: '/api/share'
      fullPath: '/api/share'
      preLoaderRoute: typeof ApiShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raw/$id': {
      id: '/api/raw/$id'
      path: '/api/raw/$id'
      fullPath: '/api/raw/$id'
      preLoaderRoute: typeof ApiRawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$id': {
      id: '/api/og/$id'
      path: '/api/og/$id'
      fullPath: '/api/og/$id'
      preLoaderRoute: typeof ApiOgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiShareRoute: ApiShareRoute,
  SIdRoute: SIdRoute,
  ApiOgIdRoute: ApiOgIdRoute,
  ApiRawIdRoute: ApiRawIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
