// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters accepted when adding a conversation listener.
 */
export type AddConversationListenerParams = { conversationId: string };
