// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from './ConversationId';
import type { ThreadId } from './ThreadId';

export type Conversation = {
  id: ConversationId;
  threadId: ThreadId;
  rolloutPath: string | null;
  createdAt: string;
  label: string | null;
  parentConversationId: ConversationId | null;
  forkedAtNthUserMessage: number | null;
};
