// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from './ConversationId';

export type CreateMessageCommentParams = {
  id: string | null;
  conversationId: ConversationId;
  cellId: string;
  selectionText: string;
  selectionPreview: string;
  selectionStartOffset: number | null;
  selectionEndOffset: number | null;
  selectionBlockIndex: number | null;
  commentText: string;
};
