// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetRepoDiffParams = {
  workspacePath: string;
  baseRef: string;
  targetRef: string | null;
  /**
   * When true, diff `base_ref` against the working tree (ignores `target_ref`).
   */
  includeWorktree: boolean;
};
