// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from './ConversationId';

export type GetTurnDiffRangeParams = {
  conversationId: ConversationId;
  baseEventId: string | null;
  targetEventId: string;
};
