// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandoffFileRef } from './HandoffFileRef';

export type HandoffPlanEvent = {
  title: string | null;
  handoff_prompt: string;
  preview: string | null;
  relevant_files: Array<HandoffFileRef>;
};
