// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnSnapshotDescriptor } from './TurnSnapshotDescriptor';

export type ListTurnSnapshotsResponse = {
  disabled: boolean;
  baseCommitId: string | null;
  snapshots: Array<TurnSnapshotDescriptor>;
};
