// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMention } from './ThreadMention';

export type ReadThreadEndEvent = {
  /**
   * Identifier for the read_thread tool call.
   */
  call_id: string;
  /**
   * Turn ID that this call belongs to.
   * Uses `#[serde(default)]` for backwards compatibility.
   */
  turn_id: string;
  /**
   * The thread reference requested (UUID string for local threads).
   */
  thread_ref: string;
  /**
   * The user-provided instructions (may be truncated in UI if long).
   */
  instructions: string;
  /**
   * Final extracted summary when successful.
   */
  summary: string;
  /**
   * Thread references returned to the UI.
   */
  mentions: Array<ThreadMention>;
  /**
   * Whether the tool execution succeeded.
   */
  success: boolean;
  /**
   * Error message when `success` is false.
   */
  error_message: string | null;
};
