// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewTarget } from './ReviewTarget';

/**
 * Parameters accepted when triggering a review-map op.
 */
export type ReviewMapConversationParams = {
  conversationId: string;
  target: ReviewTarget;
  userFacingHint?: string;
};
