// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewTarget } from './ReviewTarget';

/**
 * Review-map request sent to the review-map session.
 */
export type ReviewMapRequest = {
  target: ReviewTarget;
  user_facing_hint?: string;
};
