// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewMapFileChangeType } from './ReviewMapFileChangeType';

export type ReviewMapFile = {
  path: string;
  change_type?: ReviewMapFileChangeType;
  summary: string;
  concepts: Array<string>;
};
