// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewMapConcept = {
  id: string;
  title: string;
  summary: string;
  primary_files: Array<string>;
  risks: Array<string>;
  questions: Array<string>;
};
