// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewMapConcept } from './ReviewMapConcept';
import type { ReviewMapStep } from './ReviewMapStep';
import type { ReviewMapTrace } from './ReviewMapTrace';

/**
 * Structured review map result produced by a child review-map session.
 */
export type ReviewMapOutputEvent = {
  /**
   * Schema version for forwards-compatible rendering.
   */
  version: number;
  title: string;
  summary: string;
  concepts: Array<ReviewMapConcept>;
  traces: Array<ReviewMapTrace>;
  steps: Array<ReviewMapStep>;
};
