// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewMapEdgeType } from './ReviewMapEdgeType';
import type { ReviewMapNodeRef } from './ReviewMapNodeRef';

export type ReviewMapEdge = {
  from: ReviewMapNodeRef;
  to: ReviewMapNodeRef;
  type: ReviewMapEdgeType;
  rationale: string;
};
