// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewMapCodeRef } from './ReviewMapCodeRef';

export type ReviewMapStep = {
  /**
   * Short stable ID (e.g. "r3", "12a") used for navigation and cross-links.
   */
  id: string;
  title: string;
  /**
   * Why this step matters and what to verify.
   */
  rationale: string;
  suggested_questions: Array<string>;
  concept_ids: Array<string>;
  code_refs: Array<ReviewMapCodeRef>;
  next_step_id?: string;
  also_step_ids: Array<string>;
};
