// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewMapCodeRefKind } from './ReviewMapCodeRefKind';
import type { ReviewMapLineRange } from './ReviewMapLineRange';

export type ReviewMapCodeRef = {
  /**
   * Stable identifier within the step.
   */
  id: string;
  /**
   * Human-friendly label shown in the UI (e.g. "Validate input", "Write path", "Test").
   */
  label: string;
  file_path: string;
  kind: ReviewMapCodeRefKind;
  line_range?: ReviewMapLineRange;
  symbol?: string;
  hunk_header?: string;
  notes?: string;
};
