// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewMapConcept } from './ReviewMapConcept';
import type { ReviewMapEdge } from './ReviewMapEdge';
import type { ReviewMapFile } from './ReviewMapFile';
import type { ReviewMapReviewStep } from './ReviewMapReviewStep';

/**
 * Structured review map result produced by a child review-map session.
 */
export type ReviewMapOutputEvent = {
  /**
   * Schema version for forwards-compatible rendering.
   */
  version: number;
  title: string;
  summary: string;
  concepts: Array<ReviewMapConcept>;
  files: Array<ReviewMapFile>;
  edges: Array<ReviewMapEdge>;
  review_order: Array<ReviewMapReviewStep>;
};
