// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewMapLineRange = {
  /**
   * Inclusive 1-based line range.
   */
  start: number;
  /**
   * Inclusive 1-based line range.
   */
  end: number;
};
