// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewMapNodeRef } from './ReviewMapNodeRef';

export type ReviewMapReviewStep = {
  node: ReviewMapNodeRef;
  why: string;
  suggested_questions: Array<string>;
};
