// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SavePastedImageParams = {
  workspacePath: string;
  dataBase64: string;
  fileName: string | null;
  mimeType: string | null;
  width: number | null;
  height: number | null;
};
