// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSearchHit } from './ThreadSearchHit';

export type SearchThreadsResponse = {
  hits: Array<ThreadSearchHit>;
  isIndexing: boolean;
  indexError: string | null;
};
