// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadMention = {
  /**
   * Unique identifier for the target thread (UUID string for local threads).
   */
  thread_id: string;
  /**
   * Human-friendly label shown in the UI (typically the thread title).
   */
  label: string;
};
