// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadSearchHit = {
  threadId: string;
  title: string | null;
  preview: string;
  timestamp: string;
  snippet: string | null;
  score: number;
};
