// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallStatus } from './ToolCallStatus';
import type { ToolRef } from './ToolRef';

export type ToolCallEndEvent = {
  call_id: string;
  tool: ToolRef;
  status: ToolCallStatus;
  duration: string;
  /**
   * Truncated preview of the tool output, if any.
   */
  output_preview: string;
  /**
   * Truncated error string when `status` is `error`.
   */
  error_message: string;
};
