// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolRef } from './ToolRef';

export type ToolCallBeginEvent = {
  call_id: string;
  tool: ToolRef;
  /**
   * Truncated JSON or freeform preview of invocation arguments.
   */
  arguments_preview: string;
};
