// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuiltinToolName } from './BuiltinToolName';

export type ToolRef =
  | { kind: 'builtin'; name: BuiltinToolName }
  | { kind: 'mcp'; name: string }
  | { kind: 'other'; name: string };
