// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from './AuthMode';

/**
 * Authentication status returned to the renderer.
 */
export type AuthState = {
  isAuthenticated: boolean;
  mode: AuthMode | null;
  email: string | null;
  planType: string | null;
  requiresAuth: boolean;
  lastError: string | null;
};
