// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthState } from './AuthState';
import type { ConversationEventPayload } from './ConversationEventPayload';

/**
 * Union of events emitted to the renderer.
 */
export type CodexEvent =
  | { kind: 'conversation-event'; payload: ConversationEventPayload }
  | { kind: 'auth-updated'; payload: AuthState };
