// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskForApproval } from './AskForApproval';
import type { ReasoningEffort } from './ReasoningEffort';
import type { ReasoningSummary } from './ReasoningSummary';
import type { SandboxMode } from './SandboxMode';

/**
 * Serialized composer configuration for a conversation.
 */
export type ComposerTurnConfigPayload = {
  model: string | null;
  reasoningEffort: ReasoningEffort | null;
  summary: ReasoningSummary | null;
  sandbox: SandboxMode | null;
  approval: AskForApproval | null;
};
