// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnDiffSnapshot } from './TurnDiffSnapshot';

/**
 * Snapshot of runtime metadata for a conversation stream.
 */
export type ConversationRuntimeSnapshot = {
  activeTurnStartedAt: string | null;
  contextTokensInWindow: bigint | null;
  maxContextWindow: bigint | null;
  statusHeader: string | null;
  latestTurnDiff: TurnDiffSnapshot | null;
};
