// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from './ConversationId';

/**
 * Row displayed in the conversation list.
 */
export type ConversationSummary = {
  conversationId: ConversationId;
  path: string;
  cwd: string;
  preview: string;
  timestamp: string | null;
};
