// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventMsg } from './EventMsg';

/**
 * Payload emitted over the shared codex event channel.
 */
export type ConversationEventPayload = {
  conversationId: string;
  eventId: string;
  event: EventMsg;
};
