// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedCommand } from './ParsedCommand';

export type ExecCommandBeginEvent = {
  /**
   * Identifier so this can be paired with the ExecCommandEnd event.
   */
  call_id: string;
  /**
   * The command to be executed.
   */
  command: Array<string>;
  /**
   * The command's working directory if not the default cwd for the agent.
   */
  cwd: string;
  parsed_cmd: Array<ParsedCommand>;
  /**
   * True when this exec was initiated directly by the user (e.g. bang command),
   * not by the agent/model. Defaults to false for backwards compatibility.
   */
  is_user_shell_command: boolean;
};
