// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForkId } from './ForkId';
import type { ForkPoint } from './ForkPoint';
import type { ThreadId } from './ThreadId';

export type Fork = {
  id: ForkId;
  threadId: ThreadId;
  rolloutPath: string;
  createdAt: string;
  label: string | null;
  forkPoint: ForkPoint | null;
};
