// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningSummary } from './ReasoningSummary';
import type { SessionConfiguredEvent } from './SessionConfiguredEvent';

/**
 * Response returned after initializing a conversation stream.
 */
export type InitializeConversationResponse = {
  sessionConfigured: SessionConfiguredEvent;
  reasoningSummary: ReasoningSummary;
};
