// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadRollout } from './ThreadRollout';

export type ListThreadRolloutsResponse = {
  threadId: string;
  currentConversationId: string;
  rollouts: Array<ThreadRollout>;
};
