// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskForApproval } from './AskForApproval';
import type { SandboxMode } from './SandboxMode';
import type { JsonValue } from './serde_json/JsonValue';

/**
 * Options accepted when creating a new conversation.
 */
export type NewConversationParams = {
  model: string | null;
  profile: string | null;
  cwd: string | null;
  approvalPolicy: AskForApproval | null;
  sandbox: SandboxMode | null;
  config: { [key in string]?: JsonValue } | null;
  baseInstructions: string | null;
  includeApplyPatchTool: boolean | null;
};
