// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from './ConversationId';

/**
 * Parameters accepted when responding to an approval request.
 */
export type RespondApprovalParams = {
  conversationId: ConversationId;
  eventId: string;
  decision: string;
  approvalType: string;
};
