// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskForApproval } from './AskForApproval';
import type { InputItem } from './InputItem';
import type { ReasoningEffort } from './ReasoningEffort';
import type { ReasoningSummary } from './ReasoningSummary';
import type { SandboxMode } from './SandboxMode';

/**
 * Parameters accepted when sending a user message.
 */
export type SendUserMessageParams = {
  conversationId: string;
  items: Array<InputItem>;
  model: string | null;
  reasoningEffort: ReasoningEffort | null;
  summary: ReasoningSummary | null;
  sandbox: SandboxMode | null;
  approvalPolicy: AskForApproval | null;
};
