// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from './ConversationId';
import type { ReasoningSummary } from './ReasoningSummary';
import type { SessionConfiguredEvent } from './SessionConfiguredEvent';

export type SwitchThreadRolloutResponse = {
  conversationId: ConversationId;
  sessionConfigured: SessionConfiguredEvent | null;
  reasoningSummary: ReasoningSummary | null;
};
