// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadMetadataPayload = {
  threadId: string;
  conversationId: string;
  workspacePath: string;
  title: string | null;
  preview: string | null;
  timestamp: string;
};
