// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadSummary = {
  threadId: string;
  workspacePath: string;
  currentConversationId: string;
  preview: string;
  title: string | null;
  timestamp: string;
  forkCount: number;
};
