// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRollout = {
  conversationId: string;
  rolloutPath: string;
  createdAt: string;
  label: string | null;
  forkedFromConversationId: string | null;
  forkedFromNthUserMessage: number | null;
};
