// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of the most recent turn diff emitted by the runtime.
 */
export type TurnDiffSnapshot = {
  eventId: string;
  timestamp: string;
  unifiedDiff: string;
  turnNumber: number;
};
