// GENERATED CODE! DO NOT MODIFY BY HAND!
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters accepted by workspace navigation commands.
 */
export type WorkspacePathParams = { workspacePath: string };
